name "reveal-md"
maintainer "JJ Asghar"
maintainer_email "jj@chef.io"
license "Apache 2.0"
description "Sets everything you need up for reveal-md"
version "0.1.0"
issues_url "https://github.com/jjasghar/reveal-md-cookbook/issues"
source_url "https://github.com/jjasghar/reveal-md-cookbook/"
